### ISSUE TITLE
use Throwable results in error

### ISSUE THREAD

**Issue by josephstover** [rjbs/Throwable#19] opened 2016-09-13 21:06 UTC
I apologize if this is a bad bug report.  I know very little about Perl, but a program I use is written in Perl and I was having trouble getting part of it to work.  The error seems to originate in the Throwable module

If I run

`perl -e 'use Throwable'`

I get the following output

```
String found where operator expected at /usr/share/perl5/vendor_perl/Throwable.pm line 42, near "has 'previous_exception'"
    (Do you need to predeclare has?)
syntax error at /usr/share/perl5/vendor_perl/Throwable.pm line 42, near "has 'previous_exception'"
BEGIN not safe after errors--compilation aborted at /usr/share/perl5/vendor_perl/Throwable.pm line 79.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

I'm happy to provide any additional information that would be helpful.

Thanks

**Comment by rjbs** [comment] 2016-09-15 02:32
I'm afraid I can't reproduce this.  The fact that "has" isn't being found makes this sound like some sort of catastrophic failure of installation.

How did you install Throwable?

**Comment by dillongilmore** [comment] 2016-09-25 00:11
Hi, also seeing the exact same issue. I'm on ArchLinux attempting to deploy Bugzilla. Installation was done done via Bugzilla's `install-module.pl --all` command. Trying to debug, but I'm not sure where the `has` command is supposed to come from.

**Comment by lprovot** [comment] 2016-09-28 09:55
Hi, I also had this issue (and I'm also on ArchLinux) with auto-multiple-choice. I don't really know what's going wrong but downgrading perl-moo from 2.002004-1 to 2.000002-1 solved the problem. Hope this can help to find the root of this issue.

**Comment by rjbs** [comment] 2016-09-29 01:09
"has" is supplied by Moo::Role.

**Comment by jnbek** [comment] 2016-10-10 16:33
So, it's a Moo or Moo::Role bug? I'm seeing this on a few other modules too ( also on Arch Linux )

**Comment by rjbs** [comment] 2016-10-27 22:03
I can't reproduce this in any way on my Debian or OS X boxes.  I can't see anything indicating Arch has made changes to their versions of these libraries.  I am curious:  if you build a new Perl from scratch on those boxes, then install Moo and Throwable, can you load the library?

If worse comes to worst, I can make an Arch Linux VM, maybe…

**Comment by rjbs** [comment] 2016-10-27 22:07
One of the Moo maintainers suggested that Arch may be giving you a too-old, incompatible Role::Tiny.  Moo v2.002004 requires Role::Tiny v2.000002, which is higher than what Arch requires for it.  What version of Role::Tiny do you have installed in a failing configuration?

If less than v2.000002, then the bug may be in the prereqs in Arch.

**Comment by jnbek** [comment] 2016-11-03 00:45
I currently have perl-role-tiny 2.000003-1 installed, but the maintainer just released perl-role-tiny 2.000003-2 a few days ago... 

Updating both packages:

```
community/perl-moo        2.001001-1   2.002004-1     0.00 MiB                                                                                              
community/perl-role-tiny  2.000003-1   2.000003-2     0.00 MiB       0.01 MiB
```

Fixed the problem for me:
```
([J:0]jnbek@ecclesiastes3[~]% perl -MThrowable -e1                                                                                    [11/02/16][18:38:53])
([J:0]jnbek@ecclesiastes3[~]% perl -e 'use Throwable'                                                                                 [11/02/16][18:39:48])
([J:0]jnbek@ecclesiastes3[~]%                                                                                                         [11/02/16][18:41:59])
```

**Comment by rjbs** [comment] 2016-11-06 01:13
So, this sounds to me like something that needs fixing in their package repository's prereqs info.  Do you agree?  Can you pass this information on to whoever is appropriate?

**Comment by jnbek** [comment] 2016-11-07 14:36
Yea, I will discuss with the packager about more fine grained dependency tracking on moo/role-tiny. It is worth nothing that ( and this isn't your problem, just venting ) that a package breaking change should be given more of a version bump than 1/10millionth of a bump :D #just_sayin. ( Speaking of the Role::Tiny update that broke Moo ).

**Comment by haarg** [comment] 2016-11-07 18:55
The Role::Tiny update didn't break Moo.  The new Moo required a change from the updated Role::Tiny.  In this case though, it was a minor internal refactoring, not just a bug fix.  So yes, I should have bumped the minor version.  Moo and Role::Tiny versions are meant to be semver-style major.minor.patch, but formatted as perl style numeric versions.

**Comment by jnbek** [comment] 2016-11-07 20:48
Akk!! Sorry @haarg my choice of wording was ill considered and my sincere apology. :D Regardless, though, I'll get with the Arch PKGBUILD maintainers and discuss better version enforcement on the two packages. I used to be the maintainer of both when they were part of the AUR, but they got promoted to Official Community packages. The new maintainer still more or less uses my PKGBUILDs, so part of that fault rests with me. Either way, I think this bug can be closed and further discussion can occur on another medium, such as PerlIRC if the participants so desire.

**Comment by rjbs** [comment] 2016-11-08 21:29
Thanks to everyone involved in sorting this out.  I'm closing the issue.

**Closed by rjbs** 2016-11-08 21:29 UTC
